# Generated by Django 5.1.6 on 2025-04-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="guarantee_period",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="shipping_time",
        ),
    ]
