# Generated by Django 5.1.6 on 2025-03-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="vendor_username",
        ),
    ]
