# Generated by Django 5.1.6 on 2025-04-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0002_remove_vendor_guarantee_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryagent",
            name="city",
            field=models.CharField(choices=[], default="Casablanca", max_length=56),
        ),
    ]
