# Generated by Django 5.1.6 on 2025-04-24 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0004_deliveryagent_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryagent",
            old_name="profile_image",
            new_name="profile_picture",
        ),
    ]
