# Generated by Django 5.1.6 on 2025-04-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0005_rename_profile_image_deliveryagent_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryagent",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="delivery_agents/"
            ),
        ),
    ]
