# Generated by Django 5.1.6 on 2025-04-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0006_alter_deliveryagent_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="amount_of_canceled_cart_order_items",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
