# Generated by Django 5.1.6 on 2025-04-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0007_client_amount_of_canceled_cart_order_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliveryagent",
            name="city",
        ),
        migrations.AlterField(
            model_name="vendor",
            name="city",
            field=models.CharField(
                choices=[("CS", "Casablanca"), ("RB", "Rabat")], max_length=128
            ),
        ),
    ]
