# Generated by Django 5.1.6 on 2025-04-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0008_remove_deliveryagent_city_alter_vendor_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryagent",
            name="city",
            field=models.CharField(choices=[], default="CS", max_length=56),
        ),
    ]
