# Generated by Django 5.1.6 on 2025-04-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="potential_guarantee_period",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="potential_shipping_period",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
