# Generated by Django 5.1.6 on 2025-05-12 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalorder",
            name="delivery_option",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
