# Generated by Django 5.1.6 on 2025-03-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalorder",
            name="is_payed",
            field=models.BooleanField(default=False),
        ),
    ]
