# Generated by Django 5.1.6 on 2025-05-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0002_alter_globalorder_delivery_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodproduct",
            name="description",
            field=models.CharField(default="", max_length=80),
        ),
    ]
