# Generated by Django 5.1.6 on 2025-05-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0003_alter_foodproduct_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorder",
            name="food_order_status",
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("confirmed", "Confirmed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                    ("returned", "Returned"),
                ],
                default="processing",
                max_length=128,
            ),
        ),
    ]
