# Generated by Django 5.1.6 on 2025-04-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0003_sector_category_sector"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategoryTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "SubCategory",
                    models.ManyToManyField(
                        related_name="tags", to="ecomapp.subcategory"
                    ),
                ),
            ],
        ),
    ]
