# Generated by Django 5.1.6 on 2025-04-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0004_subcategorytag"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="delivery_option",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="globalorder",
            name="delivery_option",
            field=models.BooleanField(default=False),
        ),
    ]
