# Generated by Django 5.1.6 on 2025-05-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0004_remove_cartorder_food_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
