# Generated by Django 5.1.6 on 2025-04-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0005_cartorder_delivery_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalorder",
            name="city",
            field=models.CharField(choices=[], default="Casablanca", max_length=56),
        ),
        migrations.AddField(
            model_name="globalorder",
            name="country",
            field=models.CharField(default="Morocco", max_length=56),
        ),
        migrations.AlterField(
            model_name="globalorder",
            name="address",
            field=models.TextField(default="Casablanca"),
        ),
    ]
