# Generated by Django 5.1.6 on 2025-04-25 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0006_globalorder_city_globalorder_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorderitem",
            name="cart_order_item_status",
        ),
        migrations.RemoveField(
            model_name="cartorderitem",
            name="facture",
        ),
        migrations.RemoveField(
            model_name="cartorderitem",
            name="potential_delivery_days",
        ),
        migrations.RemoveField(
            model_name="cartorderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cartorderitem",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="claimedorder",
            name="is_canceled",
        ),
        migrations.RemoveField(
            model_name="product",
            name="potential_delivery_days",
        ),
        migrations.RemoveField(
            model_name="product",
            name="potential_shipping_period",
        ),
        migrations.AddField(
            model_name="cartorder",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="is_canceled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("process", "Processing"),
                    ("confirmed", "Confirmed"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                    ("returned", "Returned"),
                ],
                default="processing",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="is_canceled_by_vendor",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="claimedorder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claimed_orders",
                to="ecomapp.cartorder",
            ),
        ),
        migrations.CreateModel(
            name="CancellationRequestByDeliveryAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        choices=[
                            ("VNR", "vendor is not reachable"),
                            ("CNR", "client is not reachable"),
                            ("ANR", "delivery agent is not reachable"),
                            ("OTHERS", "others"),
                        ],
                        max_length=128,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "claimed_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancellation_requests",
                        to="ecomapp.claimedorder",
                    ),
                ),
            ],
        ),
    ]
