# Generated by Django 5.1.6 on 2025-05-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0006_cartitem_size_productsize"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="long_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="productsize",
            constraint=models.UniqueConstraint(
                fields=("product", "size"), name="unique_product_size"
            ),
        ),
    ]
