# Generated by Django 5.1.6 on 2025-05-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0007_product_long_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodproduct",
            name="long_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
