# Generated by Django 5.1.6 on 2025-04-25 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0007_remove_cartorderitem_cart_order_item_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancellationrequestbydeliveryagent",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cancellationrequestbydeliveryagent",
            name="claimed_order",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancellation_request",
                to="ecomapp.claimedorder",
            ),
        ),
    ]
