# Generated by Django 5.1.6 on 2025-05-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0008_foodproduct_long_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorder",
            name="total_payed",
        ),
        migrations.AlterField(
            model_name="globalorder",
            name="address",
            field=models.TextField(),
        ),
    ]
