# Generated by Django 5.1.6 on 2025-04-25 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ecomapp", "0009_clientstrike_notification_vendorstrike"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="claimedorder",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("claimed from vendor", "Claimed from vendor"),
                    ("on the way to destination", "On the way to destination"),
                    ("delivered", "Delivered"),
                    ("returned", "Returned"),
                    ("canceled", "Canceled"),
                ],
                default="processing",
                max_length=56,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
