# Generated by Django 5.1.6 on 2025-05-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0009_remove_cartorder_total_payed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="total_payed",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
