# Generated by Django 5.1.6 on 2025-05-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0010_cartorder_total_payed"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="food_products",
            field=models.ManyToManyField(
                related_name="wishlists", to="ecomapp.foodproduct"
            ),
        ),
    ]
