# Generated by Django 5.1.6 on 2025-04-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0010_notification_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_product_in_cart",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("order", "Order"),
                    ("message", "Message"),
                    ("cart_order_item", "Cart_order_item"),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
