# Generated by Django 5.1.6 on 2025-04-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecomapp", "0011_remove_cartitem_unique_product_in_cart_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="claimedorder",
            old_name="expiration_time_out",
            new_name="expiration_time_date",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("order", "Order"),
                    ("message", "Message"),
                    ("cart_order_item", "Cart_order_item"),
                    ("claimed_order", "Claimed_order"),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
