# Generated by Django 5.1.6 on 2025-04-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecomapp",
            "0013_rename_expiration_time_date_claimedorder_expiration_date_time",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimedorder",
            name="expiration_date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
